// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSjVphk0xNHuunpCAe3C7_DvbjfpcuHgY',
    appId: '1:912374552255:web:ace4a0f737572ab96a980a',
    messagingSenderId: '912374552255',
    projectId: 'diabary',
    authDomain: 'diabary.firebaseapp.com',
    storageBucket: 'diabary.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkNhpKEpGrSdnuVaR2k8TbmgGC2okZs3c',
    appId: '1:912374552255:android:15169dd4170201b16a980a',
    messagingSenderId: '912374552255',
    projectId: 'diabary',
    storageBucket: 'diabary.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSjVphk0xNHuunpCAe3C7_DvbjfpcuHgY',
    appId: '1:912374552255:web:58b917e0f3e6470f6a980a',
    messagingSenderId: '912374552255',
    projectId: 'diabary',
    authDomain: 'diabary.firebaseapp.com',
    storageBucket: 'diabary.firebasestorage.app',
  );
}
